openapi: "3.0.3"
info:
  title: USTC IT Asset Management API
  version: "1.0"
  description: "The USTC IT Asset Management API provides secure, centralized access to asset data stored, enabling clients to retrieve, update, and manage assets directly within support workflows"

servers:
  - url: https://ustc-itam-apis-prod.azurewebsites.net/api
    description: Production

  - url: https://ustc-itam-apis-test.azurewebsites.net/api
    description: Test

components:
  parameters:
    AuthorizationHeader:
      in: header
      name: Authorization
      required: true
      description: >
        Bearer token authentication header.
        Format: "Bearer <token>"
      schema:
        type: string
      example: "Bearer <token>"

  securitySchemes:
    clientCredentialsAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/{{TENTANTID}}/oauth2/v2.0/token
          scopes:
            api://ustc-itam-apis-authentication-prod/.default: Use Production
            api://ustc-itam-apis-authentication-dev/.default: Use Development

      description: >
        Send the token in the Authorization header:
        "Authorization: Bearer <token>"

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Dataverse query failed"
            data: "Request failed with status code 400"

    BadRequestNoBody:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Missing body within request"
            data: null

    Unauthorized:
      description: Unauthorized – Authentication required
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "IDX10223: Lifetime validation failed. The token is expired"
            data: null

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Unauthorized"
            data: null

    NotFound:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Resource not found"
            data: null

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Dataverse asset lookup failed"
            data: null

  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        data:
          nullable: true

    Asset:
      type: object
      properties:
        activation:
          type: boolean
          nullable: true
        assetName:
          type: string
        condition:
          type: string
          enum: [Excellent, Good, Poor, Garbage, Damaged, New]
        itemStatus:
          type: string
          enum:
            [
              Assigned,
              Available,
              Kiosk,
              Recycled,
              Decommissioned,
              Repair,
              Inoperative,
              Unknown,
              "Excess in Depot",
            ]
        location:
          type: string
          nullable: true
        osVersion:
          type: string
          nullable: true
          enum: [Windows 11 23H2, Windows 11 24H2, Windows 10]
        phone:
          type: string
          nullable: true
        user:
          type: object
          nullable: true
          properties:
            email:
              type: string
              format: email
            isActive:
              type: boolean
            isContractor:
              type: boolean
            phone:
              type: string
              nullable: true
            jobTitle:
              type: string
            location:
              type: string
            name:
              type: string
    JobTitles:
      type: object
      properties:
        jobTitle:
          type: string
          example: "Engineer"
          nullable: false
        requiredAssets:
          nullable: true
          type: array
          items:
            type: object
            properties:
              assetType:
                type: string
                example: "Monitor"
                description: Type/category of the asset (e.g., Laptop, Docking Station)
              minimumQuantity:
                type: integer
                example: 1
                description: Minimum number of assets required
              maximumQuantity:
                type: integer
                example: 2
                description: Maximum number of assets allowed
              models:
                type: array
                items:
                  type: object
                  properties:
                    modelName:
                      type: string
                      example: "EliteDisplay 231i"
                      description: Name of the specific Model
                    modelMaximum:
                      type: integer
                      example: 2
                      description: Maximum number of assets required for this specific model
                    modelMinimum:
                      type: integer
                      example: 1
                      description: Minimum number of assets required for this specfic model
security:
  - clientCredentialsAuth: []
paths:
  /v1/assets/{assetId}:
    get:
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/AuthorizationHeader"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Asset"
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/assignments/{userId}:
    post:
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - name: userId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - zendeskTicketId
                - condition
              properties:
                notes:
                  type: string
                  example: "these are notes I want to add"
                zendeskTicketId:
                  type: integer
                condition:
                  type: string
                  enum: [Excellent, Good, Poor, Garbage, Damaged, New]
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "400": { $ref: "#/components/responses/BadRequestNoBody" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/assignments:
    delete:
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - zendeskTicketId
                - condition
              properties:
                notes:
                  type: string
                  example: "these are notes I want to add"
                zendeskTicketId:
                  type: integer
                condition:
                  type: string
                  enum: [Excellent, Good, Poor, Garbage, Damaged, New]
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "400": { $ref: "#/components/responses/BadRequestNoBody" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/location/{locationId}:
    post:
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - name: locationId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/location:
    delete:
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/users/email/{email}/assets:
    get:
      parameters:
        - name: email
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Returns all assets assigned to a user
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Asset"
        "401": { $ref: "#/components/responses/Unauthorized" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/job-titles/{jobTitleId}/requirements:
    get:
      parameters:
        - name: jobTitleId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Returns all assets required by Job Title Id
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        $ref: "#/components/schemas/JobTitles"
        "401": { $ref: "#/components/responses/Unauthorized" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }
