openapi: "3.0.3"
info:
  title: USTC IT Asset Management API
  version: "1.0"
  description: "The USTC IT Asset Management API provides secure, centralized access to asset data stored, enabling clients to retrieve, update, and manage assets directly within support workflows"

servers:
  - url: https://ustc-itam-apis-prod.azurewebsites.net/api
    description: Production

  - url: https://ustc-itam-apis-test.azurewebsites.net/api
    description: Test

components:
  parameters:
    AuthorizationHeader:
      in: header
      name: Authorization
      required: true
      description: >
        Bearer token authentication header.
        Format: "Bearer <token>"
      schema:
        type: string
      example: "Bearer <token>"

  securitySchemes:
    clientCredentialsAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/{{TENTANTID}}/oauth2/v2.0/token
          scopes:
            api://ustc-itam-apis-authentication-prod/.default: Use Production
            api://ustc-itam-apis-authentication-dev/.default: Use Development

      description: >
        Send the token in the Authorization header:
        "Authorization: Bearer <token>"

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Dataverse query failed"
            data: "Request failed with status code 400"

    Unauthorized:
      description: Unauthorized – Authentication required
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "IDX10223: Lifetime validation failed. The token is expired"
            data: null

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Unauthorized"
            data: null

    NotFound:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Resource not found"
            data: null

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            message: "Dataverse asset lookup failed"
            data: null

  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        data:
          nullable: true

    Asset:
      type: object
      properties:
        activation:
          type: boolean
          nullable: true
        assetName:
          type: string
          example: "EliteDisplay 231i #22"
        condition:
          type: string
          example: Good
          enum: [Excellent, Good, Poor, Garbage, Damaged, New]
        itemStatus:
          type: string
          enum:
            [
              Assigned,
              Available,
              Kiosk,
              Recycled,
              Decommissioned,
              Repair,
              Inoperative,
              Unknown,
              "Excess in Depot",
            ]
        location:
          type: string
          example: 316
          nullable: true
        modelInfo:
          type: object
          nullable: true
          properties:
            warrantyInformation:
              type: string
              example: "Warranty valid until 01/01/2025"
        osVersion:
          type: string
          example: Windows 11 24H2
          nullable: true
          enum: [Windows 11 23H2, Windows 11 24H2, Windows 10]
        phone:
          type: string
          example: 111-111-1111
          nullable: true
        user:
          type: object
          nullable: true
          properties:
            email:
              type: string
              example: email@ustaxcourt.gov
              format: email
            isActive:
              type: boolean
              example: true
            isContractor:
              type: boolean
              example: false
            phone:
              type: string
              example: 111-111-1111
              nullable: true
            jobTitle:
              type: string
              example: Accountant
            location:
              type: string
              example: 316
            name:
              type: string
              example: Joe Doe
    JobTitles:
      type: object
      properties:
        jobTitle:
          type: string
          example: "Engineer"
          nullable: false
        requiredAssets:
          nullable: true
          type: array
          items:
            type: object
            properties:
              assetType:
                type: string
                example: "Monitor"
                description: Type/category of the asset (e.g., Laptop, Docking Station)
              minimumQuantity:
                type: integer
                example: 1
                description: Minimum number of assets required
              maximumQuantity:
                type: integer
                example: 2
                description: Maximum number of assets allowed
              models:
                type: array
                items:
                  type: object
                  properties:
                    modelName:
                      type: string
                      example: "EliteDisplay 231i"
                      description: Name of the specific Model
                    modelMaximum:
                      type: integer
                      example: 2
                      description: Maximum number of assets required for this specific model
                    modelMinimum:
                      type: integer
                      example: 1
                      description: Minimum number of assets required for this specfic model
security:
  - clientCredentialsAuth: []
paths:
  /v1/assets/{assetId}:
    get:
      description: >
        Retrieves asset information given an asset Id. Information includes activation, asset name, asset condition, item assignment status, item location,
        item OS version, item phone number, and information about user who is assigned this asset. These includes email, activity status, contractor status, phone number,
        job title, location, and name.
        Please note: Not all assets may have these values.
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/AuthorizationHeader"

      responses:
        "200":
          description: Retrieve asset information
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Asset"
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/assignments/{userId}:
    post:
      description: >
        Assigns an asset to a user given a assetId and userId
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - name: userId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - zendeskTicketId
                - condition
              properties:
                notes:
                  type: string
                  example: "these are notes I want to add"
                zendeskTicketId:
                  type: integer
                condition:
                  type: string
                  enum: [Excellent, Good, Poor, Garbage, Damaged, New]
      responses:
        "200":
          description: Assigns user to asset
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/assignments:
    delete:
      description: >
        Removes asset assignment from a user given a assetId and userId
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - zendeskTicketId
                - condition
              properties:
                notes:
                  type: string
                  example: "these are notes I want to add"
                zendeskTicketId:
                  type: integer
                condition:
                  type: string
                  enum: [Excellent, Good, Poor, Garbage, Damaged, New]
      responses:
        "200":
          description: Removes user assignment from asset
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/location/{locationId}:
    post:
      description: >
        Assigns an location to a asset given a assetId and locationId
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - name: locationId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Adds location to asset
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/assets/{assetId}/location:
    delete:
      description: >
        Removes location from asset given a assetId
      parameters:
        - name: assetId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Removes location from asset
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: string
        "401": { $ref: "#/components/responses/Unauthorized" }
        "403": { $ref: "#/components/responses/Forbidden" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/users/email/{email}/assets:
    get:
      description: >
        Returns all assets assigned to a user
      parameters:
        - name: email
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Returns all assets assigned to a user
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Asset"
        "401": { $ref: "#/components/responses/Unauthorized" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /v1/job-titles/{jobTitleId}/requirements:
    get:
      description: >
        Returns all asset requirements given a jobTitleId
      parameters:
        - name: jobTitleId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Returns all assets required by Job Title Id
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        $ref: "#/components/schemas/JobTitles"
        "401": { $ref: "#/components/responses/Unauthorized" }
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }
