openapi: "3.0.3"
info:
  title: Query Assets
  version: "1.0"
servers:
  - url: /api
paths:
  /v1/assets/{itemguid}:
    get:
      parameters:
        - name: guid
          in: query
          description: Guid of AssetId
          required: true
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    example: "Success"
                  data:
                    type: object
                    properties:
                      activation:
                        type: boolean
                        nullable: true
                        example: null
                        enum:
                          - true
                          - false
                          - null
                      assetName:
                        type: string
                        example: "HP EliteDisplay E241i #166"
                        nullable: false
                      condition:
                        type: string
                        example: "Good"
                        nullable: false
                        enum:
                          - Excellent
                          - Good
                          - Poor
                          - Garbage
                          - Damaged
                          - New
                      itemStatus:
                        type: string
                        example: "Available"
                        nullable: false
                        enum:
                          - Assigned
                          - Available
                          - Kiosk
                          - Recycled
                          - Decommissioned
                          - Repair
                          - Inoperative
                          - Unknown
                          - Excess in Depot
                      location:
                        type: string
                        example: "G47"
                        nullable: true
                      osVersion:
                        type: string
                        nullable: true
                        example: Windows 11 23H2
                        enum:
                          - Windows 11 23H2
                          - Windows 11 24H2
                          - Windows 10
                          - null
                      phone:
                        type: string
                        nullable: true
                        example: null
                      user:
                        type: object
                        properties:
                          email:
                            type: string
                            format: email
                            example: "matthew.hung@example.com"
                          isActive:
                            type: boolean
                            example: true
                          isContractor:
                            type: boolean
                            example: true
                          phone:
                            type: string
                            example: "+1-555-123-4567"
                          jobTitle:
                            type: string
                            example: "Office 365 Engineer"
                          location:
                            type: string
                            example: "Arden, California"
                          name:
                            type: string
                            example: "Matthew Hung"

                        nullable: true

        "401":
          description: Unauthorized – Authentication required
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Missing client secret"
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Dataverse query failed"
                data: "Request failed with status code 400"
        "404":
          description: Resource Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Dataverse query failed"
                data: null
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Request failed with invalid authorization status code 403"
                data: null
  /v1/assets/{assetid}/assignments/{userid}:
    post:
      parameters:
        - name: assetid
          in: query
          description: Guid of AssetId
          required: true
          schema:
            type: string
        - name: userid
          in: query
          description: entra id of user
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Successfully updated item assignment"
                  data: "77727f32-b7b9-f011-bbd3-7c1e52177972"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Unable to update assignment due to invalid assetid or userid"
                data: null

        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Unauthorized"
                data: null
  /v1/assets/{assetid}/assignments/:
    delete:
      parameters:
        - name: assetid
          in: query
          description: Guid of AssetId
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Successfully updated item assignment"
                  data: "77727f32-b7b9-f011-bbd3-7c1e52177972"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Unable to update assignment due to invalid assetid or userid"
                data: null

        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Unauthorized"
                data: null

  /v1/assets/{assetid}/location/{locationId}:
    post:
      parameters:
        - name: assetid
          in: query
          description: Guid of AssetId
          required: true
          schema:
            type: string
        - name: locationId
          in: query
          description: Id of Location
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Successfully assigned location"
                  data: "77727f32-b7b9-f011-bbd3-7c1e52177972"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Location ID not found"
                data: null

        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
              example:
                message: "Unauthorized"
                data: null
