name: export-solution-on-dev
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  pull_request:

env:
  #edit your values here
  DEVENVIROMENTURL: ${{ secrets.DevEnviromentURL }}
  TESTENVIROMENTURL: ${{ secrets.TestEnviromentURL }}

  CLIENT_ID: ${{ secrets.DevAppId }}
  TENANT_ID: ${{ secrets.DevTenantId }}
  SOLUTION_NAME: "POCImportSolution"
  SOLUTION_EXPORTED_FOLDER: /out
  SOLUTION_FOLDER: /solution
  SOLUTION_TARGET_FOLDER: solution

  TESTCLIENT_ID: ${{ secrets.TestAppId }}
  TESTTENANT_ID: ${{ secrets.TestTenantId }}

permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install PAC
        uses: microsoft/powerplatform-actions/actions-install@latest

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@latest
        with:
          environment-url: ${{env.DEVENVIROMENTURL}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@latest
        with:
          environment-url: ${{env.DEVENVIROMENTURL}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: .${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ env.SOLUTION_NAME }}.zip
          managed: true

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@latest
        with:
          solution-file: .${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ env.SOLUTION_NAME }}.zip
          solution-folder: .${{ env.SOLUTION_FOLDER }}/${{ env.SOLUTION_NAME }}
          solution-type: "Managed"
          overwrite-files: true

      - name: Commit changes
        run: |
          git fetch origin
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git checkout deploymentToPowerPlatformTestEnv || git checkout -b deploymentToPowerPlatformTestEnv
          git add --all
          git commit -m "Deploying updates from the dev environment" --allow-empty
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase -X theirs origin deploymentToPowerPlatformTestEnv
          git push -u origin deploymentToPowerPlatformTestEnv

      - name: reautheticate as test app
        uses: microsoft/powerplatform-actions/who-am-i@latest
        with:
          environment-url: ${{env.TESTENVIROMENTURL}}
          app-id: ${{env.TESTCLIENT_ID}}
          client-secret: ${{ secrets.TESTCLIENTSECRET }}
          tenant-id: ${{env.TESTTENANT_ID}}

      - name: Pack solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: .${{ env.SOLUTION_FOLDER }}/${{ env.SOLUTION_NAME }}
          solution-file: .${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ env.SOLUTION_NAME }}.zip
          solution-type: Managed

      - name: Import solution as Managed to build env
        uses: microsoft/powerplatform-actions/import-solution@latest
        with:
          environment-url: ${{env.TESTENVIROMENTURL}}
          app-id: ${{env.TESTCLIENT_ID}}
          client-secret: ${{ secrets.TESTCLIENTSECRET }}
          tenant-id: ${{env.TESTTENANT_ID}}
          solution-file: .${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ env.SOLUTION_NAME }}.zip
          force-overwrite: true
          publish-changes: true
