name: Azure Function Test

on:
  push:
    branches:
      - main
      - automated-testing-for-api-endpoints-AT-114

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test azure-functions/tests
